export const PROVIDERS = {
  gdlsp: {
    id: "gdlsp",
    name: "GDLSP / MacCMS JSON",
    upstream: "www.gdlsp.com/api/json.php",
    discoveredFrom: "movie.cfnav.me 前端请求",
    capabilities: "列表 / 搜索 / 详情 / HLS 播放",
  },
  hstream: {
    id: "hstream",
    name: "HStream 公开目录",
    upstream: "hstream.moe + 独立媒体节点",
    discoveredFrom: "观番页来源标注与播放器调用链",
    capabilities: "目录 / 搜索 / 详情 / 多线路 MP4",
  },
  leakgallery: {
    id: "leakgallery",
    name: "LeakGallery JSON",
    upstream: "api.leakgallery.com + cdn.leakgallery.com",
    discoveredFrom: "OnlyFans 图集页来源域与公开 API",
    capabilities: "列表 / 创作者搜索 / 详情 / 图片与视频",
  },
  eporner: {
    id: "eporner",
    name: "Eporner 官方 API",
    upstream: "www.eporner.com/api/v2",
    discoveredFrom: "EPORNER 站点公开 JSON API",
    capabilities: "列表 / 搜索 / 排序 / 详情 / 官方嵌入播放",
  },
  madouai: {
    id: "madouai",
    name: "麻豆AI 公开 API",
    upstream: "www.madouai.xyz/api/v1",
    discoveredFrom: "麻豆AI 参考站前端源码中的公开上游地址",
    capabilities: "分类目录 / 搜索 / 分页 / 详情 / HLS 播放",
  },
  pmvhaven: {
    id: "pmvhaven",
    name: "PMVHaven 公开目录",
    upstream: "pmvhaven.com + pmvhavencloud.s3.eu-west-par.io.cloud.ovh.net",
    discoveredFrom: "参考 PMV 站条目 ID、目录字段与媒体 CDN 的逐项同源核对",
    capabilities: "目录 / 搜索 / 分页 / 标签 / 详情 / MP4 与 HLS 播放",
  },
  iptvorg: {
    id: "iptvorg",
    name: "iptv-org 开放频道库",
    upstream: "iptv-org.github.io/api",
    discoveredFrom: "iptv-org 官方公开 API 与播放列表",
    capabilities: "电视直播 / 频道搜索 / 台标 / HLS 播放",
  },
  adulttv: {
    id: "adulttv",
    name: "oxax.tv + AdultIPTV 双源",
    upstream: "oxax.tv / s.oxax.tv / r.pokaz.me + cdn.adultiptv.net",
    discoveredFrom: "看TV 页面源标注、公开频道目录与播放页链路",
    capabilities: "80 路直播目录 / 搜索 / 双源 HLS / 品牌流实时解析",
  },
  redgifs: {
    id: "redgifs",
    name: "RedGifs 匿名视频 API",
    upstream: "api.redgifs.com + media.redgifs.com",
    discoveredFrom: "匿名临时令牌接口与公开媒体 CDN",
    capabilities: "列表 / 搜索 / 详情 / HD 与移动版 MP4",
  },
  tnaflix: {
    id: "tnaflix",
    name: "TNAFlix 公开目录",
    upstream: "www.tnaflix.com + TNAFlix 媒体节点",
    discoveredFrom: "用户保存的参考详情页与 TNAFlix 官方页面逐项核对",
    capabilities: "目录 / 搜索 / 分页 / 详情 / 多清晰度 MP4",
  },
  kan91: {
    id: "kan91",
    name: "91porna 公开目录",
    upstream: "91porna.com + yd-hls.utxxds.cn + tp*.xmbvxj.cn / pic.xmbvxj.cn",
    discoveredFrom: "看91 参考条目与 91porna.com 目录/搜索/详情/播放 ID 逐项同源核对",
    capabilities: "分类目录 / 搜索 / 分页 / 详情 / 图片解密代理 / AES-128 HLS 播放",
  },
  qiying: {
    id: "qiying",
    name: "91吃瓜网 实时上游",
    upstream: "agency.nsguiiwz.cc / being / act（301 → agency.qxmrdvtu.cc）+ imgpublic.ycomesc.live 图片 CDN + op.vkjyoi.cn / bgqpnx.cn 视频 CDN",
    discoveredFrom: "栖影 参考条目与 91吃瓜网 防失联页主站域名同源核对（2026-08-15 转全实时，删除 gz 镜像）",
    capabilities: "实时列表/分页 / 23 分类 / 搜索 / 详情图集 / 主站签名 HLS 播放",
  },
  mr: {
    id: "mr",
    name: "每日大赛 实时上游",
    upstream: "mrds.com / mrds66.com + imgpublic.ycomesc.live 图片 CDN + hls.dscxru.cn / ts.syjiaotong.mobi 视频 CDN",
    discoveredFrom: "看每日大赛 参考站 /api/meta 21 分类与 /api/posts 条目同源核对 mrds.com（1691 页一致）",
    capabilities: "实时列表/分页 / 21 分类 / 搜索 / 详情图集 / 主站签名 AES-128 HLS 播放",
  },
  madou: {
    id: "madou",
    name: "麻豆社 公开目录",
    upstream: "madou.club + dash.madou.club（分享页短时效 JWT + AES-128 HLS）",
    discoveredFrom: "看麻豆 参考条目 slug/分类/详情与 madou.club 逐项同源核对",
    capabilities: "分类目录 / 搜索 / 点赞·周·月排行 / 详情 / 分享页签名 HLS 播放",
  },
  miss: {
    id: "miss",
    name: "MissAV 公开目录",
    upstream: "missav.media + fourhoi.mrstcdn.store / surrit.mrstcdn.store",
    discoveredFrom: "看Miss 参考站 OpenAPI 文档与 missav.media 条目/媒体逐项同源核对",
    capabilities: "分区目录 / 搜索 / 详情 / 女优·类型·发行商索引 / 直链多码率 HLS 播放",
  },
  tx: {
    id: "tx",
    name: "糖心Vlog 公开目录",
    upstream: "tangxinvlog.pro + t.5gcdn.xyz（AES-128 HLS，同源代理转发）",
    discoveredFrom: "看糖心Vlog 参考站 API 契约与 tangxinvlog.pro 条目/媒体逐项同源核对",
    capabilities: "首页最新 / 全部作品分页 / 46 博主索引 / 博主作品页 / 详情 / 代理 AES-128 HLS 播放",
  },
  rou: {
    id: "rou",
    name: "看肉视频 公开目录",
    upstream: "rou.video + v.rn2xx.xyz（imgproxy 封面直链 / 签名 HLS 同源代理）",
    discoveredFrom: "看肉视频 参考站 API 契约（siteDomain 直接返回 rou.video）与上游 SSR 数据逐项同源核对",
    capabilities: "首页 9 分区 / 分类树 4 组 / 全量标签 / 搜索 / 详情 / 代理签名 HLS 播放",
  },
  jm: {
    id: "jm",
    name: "禁漫天堂 官方新站",
    upstream: "18mh.net（永久地址）+ 32b.azucyfo.com（免翻墙镜像）+ imgpublic.ycomesc.live 图片 CDN",
    discoveredFrom: "看禁漫天堂 参考站旧库 18comic.ink 被 CF 全站保护，官方 GitLab 仓库确认 18mh.net 为新站并完整比对分类/章节/图片链",
    capabilities: "全部/12 分类/排行/热门/最新/搜索 / 详情章节列表 / 章节图片阅读",
  },
  hj: {
    id: "hj",
    name: "海角社区 公开 API",
    upstream: "www.haijiao.com/api（三层 Base64 匿名接口）+ pic.hj*.top 加密图片 + ts10.hj*.top 视频 CDN（wasm jquery_key 密钥变换）",
    discoveredFrom: "看海角 参考站 decode.js（严格参考 Richy(2).txt 的三层 atob 契约）与官方 web 端 /js/jquery.js wasm 逆向核对",
    capabilities: "热门/分区树/分区帖子/搜索 / 详情图文 / 加密图解码 / 预览视频（wasm 变换 AES-128 HLS）",
  },
kan98: {
    id: "kan98",
    name: "98堂 dmn12 实时论坛",
    upstream: "dmn12.vip / sehuatang.net / sehuatang.org + tyjs.ypxjft.cn",
    discoveredFrom: "98.cfnav.me 页脚、源站分类/详情 HTML 与 play.php JSONP 逐项同源核对（2026-08-17）",
    capabilities: "论坛分类 / 搜索 / 详情 / data-tid-pid-vid 播放参数 / 实时 AES-128 HLS",
  },
  kanxo: {
    id: "kanxo",
    name: "香蕉视频 公开 API",
    upstream: "h5.xxoo473.org/api + mymb041.com / k18e7j.com 媒体 CDN",
    discoveredFrom: "爱看参考站 app.js 源码标注数据源 https://h5.xxoo473.org，接口/条目/媒体逐项同源核对（2026-08-17）",
    capabilities: "分类目录 / 搜索 / 排序 / 详情 / VIP 锁定 Richy 反推完整片（preview KEY → master）AES-128 HLS",
  },
  ph: {
    id: "ph",
    name: "Pornhub 公开目录（实验来源）",
    upstream: "www.pornhub.com + *.phncdn.com 媒体 CDN",
    discoveredFrom: "用户单独要求的实验来源（docs/Richy (13).txt 线索），2026-08-17 全链路实测：列表/搜索/分类/详情 SSR 直抓 + mediaDefinitions 内联 HLS + 媒体无 CORS 需同源代理",
    capabilities: "列表 / 搜索 / 分类 / 详情 / 多清晰度 HLS（同源代理）",
  },
  js9: {
    id: "js9",
    name: "看九色 91视频 实时上游",
    upstream: "jiuse.tv / 91porny.com + cdn2.jiuse3.cloud / dp.jiuse.cloud / cdn22.jiuse3.cloud / cdn.cdnkdjs.com + int.ucloud160.xyz / i.ucloud160.xyz / int.qiniuyun36.xyz",
    discoveredFrom: "看九色 参考站 /api/home 与 /api/video/video 契约同源核对 jiuse.tv（首页第一项 id b2cbcc3a… 与参考逐项一致，2026-08-18）",
    capabilities: "首页三路合并 / 14 分类 / 搜索 / 三类型详情（91自拍·精选·视频）/ 多线路 HLS 与 MP4 直连播放",
  },
  jav: {
    id: "jav",
    name: "看JAV javhd 实时上游",
    upstream: "javhd.com + /zh/player_api（匿名签发完整 4 码率签名 MP4）+ c3/c4.cdnjhd.com 媒体 CDN",
    discoveredFrom: "看JAV 参考站 /api/home sourceLink 与 /api/play 契约同源核对 javhd.com（标题逐字一致，2026-08-18；static2.javhd.com 拿到 jplayer.min.js → content-path → /zh/player_api 匿名完整源）",
    capabilities: "最新列表 / 搜索 / 详情 / 匿名签名完整 1080p MP4 直连播放（4 码率）",
  },
  avjb: {
    id: "avjb",
    name: "爱微社区 AVJB 实时上游",
    upstream: "avjb.com + list.avstatic.com 裸 CDN 分片（.jpg 伪装 2s MPEG-TS，CORS *）+ bmc2.imgclh.com 封面",
    discoveredFrom: "爱微社区参考站 kankan.cfnav.me 与 avjb.com 同源核对（卡片/视频 id 逐字一致，2026-08-18；docs/Richy (6).txt 即 AVJB 完整播放脚本）",
    capabilities: "首页 / 最新 / 分类 / 搜索 / 相册 / 详情 / 裸 CDN 分片自建 playlist 完整播放（VIP 同源匿名）",
  },
  dsd: {
    id: "dsd",
    name: "懂色帝 实时上游",
    upstream: "dsd900.com（MacCMS 10）+ /addons/vplayer/ jsfuck 签名中转 + video1 目录 CDN（AES-128 HLS，同源代理）",
    discoveredFrom: "看懂色帝 参考站站名破译「懂色帝」→ GitHub 发布页 → 地址页 dsd87.lol scrambled 反转字符串解码出主域（2026-08-18；MacCMS 路由 + player_aaaa + jsfuck sign 播放链全匿名实测）",
    capabilities: "分类目录 / 分页 / 搜索 / 详情 / jsfuck 签名 AES-128 HLS 播放（代理）",
  },
  hxc: {
    id: "hxc",
    name: "含羞草研究所 Fi11 官方 API",
    upstream: "a64d.vd9h4.com / a59e.f3de7.com（AES-256-CBC 加密匿名接口）+ 加密封面 .aes（AES-128-ECB，代理解码）",
    discoveredFrom: "看含羞草 参考站 /api/videos 条目与 Fi11 官方站（SleazyFork 456275 脚本）同源核对（2026-08-18；sign 窗口技巧实现全量播放）",
    capabilities: "推荐/5 分类 / 分页 / 搜索 / 详情 / 试看 sign 改全量 AES-128 HLS 播放（直连）",
  },
  sf: {
    id: "sf",
    name: "私房TV 实时上游",
    upstream: "www.sifangtv.cc（MacCMS 10）+ v2024.sysybf.com 明文 HLS CDN",
    discoveredFrom: "私房TV 参考站 sf.cfnav.me 取证（2026-08-19）：登录墙 SPA，/api/* 与 /js/* 匿名全 401；数据指纹（SFE/SFA 系列编号、psf0404.shop 封面、Wowza aboxVOD hex 签发）与 sifangtv.cc 不同源，其上游主站 502 不可达 → 按用户指示以 jm 模式接入独立官方站 sifangtv.cc（divergence 记录见 PROJECT-HANDBOOK）",
    capabilities: "最新 / 13 分类 / 分页 / 搜索 / 详情（播放页解析）/ 明文 HLS 直连播放",
  },
  hm: {
    id: "hm",
    name: "HAnime 萌番实时上游",
    upstream: "hanime1.com + r.jina.ai HTML relay + vdownload.hembed.com",
    discoveredFrom: "hm.cfnav.me 官方 V6 API/页面契约与 hanime1.com 公开备用域逐条核对；目录经实时 HTML relay 抓取，不使用 cfnav 私有 API 或快照",
    capabilities: "分类目录 / 搜索 / 分页 / 详情 / 标签 / 1080p/720p/480p MP4 直连播放",
  },
};

const ROUTE_CONFIGS = {
  ai: { provider: "madouai" },
  fj: { provider: "hstream" },
  lg: { provider: "leakgallery" },
  ep: { provider: "eporner" },
  movie: { provider: "gdlsp" },
  pmv: { provider: "pmvhaven" },
  tna: { provider: "tnaflix" },
  tv: { provider: "adulttv" },
  91: { provider: "kan91" },
  qiying: { provider: "qiying" },
  mr: { provider: "mr" },
  madou: { provider: "madou" },
  miss: { provider: "miss" },
  tx: { provider: "tx", preset: "home" },
  rou: { provider: "rou", preset: "home" },
  jm: { provider: "jm" },
hj: { provider: "hj" },
  98: { provider: "kan98", preset: "41" },
  xo: { provider: "kanxo" },
  "9s": { provider: "js9", preset: "home" },
  jav: { provider: "jav" },
  kankan: { provider: "avjb" },
  dsd: { provider: "dsd" },
  hxc: { provider: "hxc" },
  sf: { provider: "sf" },
  hm: { provider: "hm" },
};

export function getProviderForSite(slug) {
  const route = ROUTE_CONFIGS[slug];
  if (!route) return null;
  return { ...PROVIDERS[route.provider], preset: route.preset || "" };
}
